apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: osg-icecube-cvmfs-stash
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: osg-icecube-cvmfs-stash
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: osg-icecube-cvmfs-stash
  local:
    path: /var/lib/cvmfs-k8s/stash.osgstorage.org
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-stash
  namespace: osg-icecube
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: osg-icecube-cvmfs-stash
