apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-nodeplugin-config-osg
  namespace: cvmfs
  labels: 
    k8s-app: cvmfs-nodeplugin-config-osg
spec:
  selector:
    matchLabels:
      k8s-app: cvmfs-nodeplugin-config-osg
  template:
    metadata: 
      labels:
        k8s-app: cvmfs-nodeplugin-config-osg
    spec:
      serviceAccount: cvmfs-nodeplugin
      tolerations:
       - effect: NoSchedule
         key: nautilus.io/noceph
         operator: Exists
       - effect: NoSchedule
         key: nautilus.io/chase-ci
         operator: Exists
       - effect: NoSchedule
         key: nautilus.io/haosu
         operator: Exists
       - effect: NoSchedule
         key: nautilus.io/suncave
         operator: Exists
      containers:
      - name: cvmfs-config-osg
        image: sfiligoi/prp-osg-cvmfs:nodeplugin
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/sbin/unmount-and-terminate.sh"]
        env:
        - name: MOUNT_REPOS
          value: "config-osg.opensciencegrid.org"
        - name: SQUID_URI
          value: "http://10.98.29.184:3128"
        - name: CVMFS_REMOUNT
          value: "N"
        resources:
           limits:
             memory: 2Gi
             cpu: 1
           requests:
             memory: 50Mi
             cpu: 0.05
        volumeMounts:
        - mountPath: /cvmfs
          name:  cvmfs-base
          mountPropagation: Bidirectional
      volumes:
      - name: cvmfs-base
        hostPath:
          path: /var/lib/cvmfs-k8s
          type: DirectoryOrCreate

