apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cms-ucsd-t2-cvmfs-config-osg
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-ucsd-t2-cvmfs-config-osg
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cms-ucsd-t2-cvmfs-config-osg
  local:
    path: /var/lib/cvmfs-k8s/config-osg.opensciencegrid.org
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-config-osg
  namespace: cms-ucsd-t2
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: cms-ucsd-t2-cvmfs-config-osg

